apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  # deployment labels
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  replicas: 3
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database
  # This is pod definition
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: venkata040/mongodb:v1

